name: Scorecard supply-chain security

on:
  push:
  workflow_dispatch:

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      id-token: write
      contents: read

    steps:
      - name: Run analysis
        uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
