name: Scorecard supply-chain security

on:
  push:
  workflow_dispatch:

jobs:
  analysis:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: scorecard-results
          path: results.sarif
